### ISSUE TITLE
User Feedback: Double check code for generating photons for white bulb

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/color-vision#136] opened 2021-02-02 00:29 UTC
The photon view for the white bulb should pull from the rainbow spectrum of bulb color. That is there should be no "brown" or "pink" type colors that you don't find in sun spectrum. 

Can a developer take a look and see what is being used to generate the photons? Some look suspect as non-pure light colors: 
![image](https://user-images.githubusercontent.com/5096804/106535192-e42c5900-64b2-11eb-88cb-7016aa66a64c.png)

**Comment by kathy-phet** [comment] 2021-02-02 00:32
Assigning to CK as responsible dev to take a look at the code. @chrisklus - the photons should all be colors from this spectrum: 
![image](https://user-images.githubusercontent.com/5096804/106535464-82b8ba00-64b3-11eb-85b0-f608f73f7ba9.png)

**Comment by arouinfar** [comment] 2021-02-02 00:37
This was previously discussed in https://github.com/phetsims/color-vision/issues/96 and was elevated to a (now quite stale) issue in scenery-phet https://github.com/phetsims/scenery-phet/issues/340.

**Comment by arouinfar** [comment] 2021-02-02 00:50
@kathy-phet what's the priority of this issue? Did a client bring it to your attention?

If you pause and inspect the photon stream, it does look like there are some non-spectrum colored photons. However, it's something you have to be on the lookout for. 

It doesn't look like we've received any phethelp feedback about this specifically, though many years ago there were some comments about purple photons in the context of monochromatic light (#96 #88). I suspect the solution to this issue will be somewhat complicated and will end up touching other sims too, so it would be good to know more before @chrisklus spends much time on this.

**Comment by kathy-phet** [comment] 2021-02-02 01:31
It was a physics faculty member, training high school teachers, who brought it to my attention. 

Let's schedule a bit of time at a design meeting, after the current batch of sims that are working their way out the door are out the door. It's not particularly time-sensitive.

**Comment by pixelzoom** [comment] 2021-02-02 02:04
This looks like a relatively easy problem to fix, and took me ~5 minutes to track down.

The problem is in SingleBulbPhoto.js, where the photons are created.

With white light, a random color is chosen by calling `randomColor`:

```js
  // @public
  createPhoton( timeElapsed ) {

    // if the flashlight is on, create a new photon this animation frame
    if ( this.model.flashlightOnProperty.value ) {
      const newColor = ( this.model.lightTypeProperty.value === 'white' ) ?
                       randomColor() : VisibleColor.wavelengthToColor( this.model.flashlightWavelengthProperty.value );
```

`randomColor` is unfortunately defined like this, which generates random colors that are not visible colors:

```js
function randomColor() {
  const r = Math.floor( dotRandom.nextDouble() * 256 );
  const g = Math.floor( dotRandom.nextDouble() * 256 );
  const b = Math.floor( dotRandom.nextDouble() * 256 );
  return new Color( r, g, b, 1 );
}
```

What `randomColor` should be doing is generating a random visible wavelength, then converting it to a color.  So something like this (untested):

```js
function randomColor() {
  const randomWavelength = dotRandom.nextIntBetween( VisibleColor.MIN_WAVELENGTH, VisibleColor.MAX_WAVELENGTH );
  return VisibleColor.waveLengthToColor( wavelength );
}
```

And I would recommend renaming `randomColor` to `randomVisibleColor`.

Let me know if you want me to implement and test this fix.

**Comment by kathy-phet** [comment] 2021-02-02 04:33
@arouinfar, @pixelzoom - This looks good to me. If Amy agrees, lets go ahead. It would be nice to maintenance release into the current version, if easy.

**Comment by arouinfar** [comment] 2021-02-02 05:37
Yes, let's go for it. Sounds like @pixelzoom will be taking care of this, so reassigning.

**Comment by pixelzoom** [comment] 2021-02-02 05:40
We should also check with @chrisklus, since he's responsible dev for this sim. Would you like me to make this change, or do you want to handle it?

**Comment by pixelzoom** [comment] 2021-02-02 16:52
@arouinfar ready for verification in master or [1.3.0-dev.3](https://phet-dev.colorado.edu/html/color-vision/1.3.0-dev.3/phet/color-vision_en_phet.html).  When verified, I'll proceed with a maintenance release.

Screenshot comparisons...

1.1.23 (published version):

<img width="526" alt="screenshot_846" src="https://user-images.githubusercontent.com/3046552/106633649-40878b00-653c-11eb-91d4-00e160ae46b9.png">

1.3.0-dev.3 / master:

<img width="531" alt="screenshot_847" src="https://user-images.githubusercontent.com/3046552/106633669-43827b80-653c-11eb-8003-6fa28a83b68d.png">

**Comment by pixelzoom** [comment] 2021-02-02 17:22
Looks like there's also a PhET-iO branch for this sim.

```
% grunt release-branch-list --repo=color-vision
...
color-vision 1.1 phet
color-vision 1.2-phetio phet-io
```

So I'm need to patch and release 2 branches.

**Comment by arouinfar** [comment] 2021-02-02 18:23
@pixelzoom looks good in master. I no longer see non-spectrum colored photons in the photon view of white light.

**Comment by pixelzoom** [comment] 2021-02-02 23:10
Steps for the 1.1.24 maintence release:

```
% cd perennial
% grunt rc --repo=color-vision --brands=phet --branch=1.1
// wait for completion email from build server
// manually test 1.1.24-rc.1 at https://phet-dev.colorado.edu/html/color-vision/1.1.24-rc.1
% grunt production --repo=color-vision --brands=phet --branch=1.1
// wait for completion email from build server
// manually test 1.1.24 for English and a few other locales at https://phet.colorado.edu/en/simulation/color-vision
```

**Comment by pixelzoom** [comment] 2021-02-03 00:00
Cherry-picking was not possible because the color-vision 1.1 and 1.2-phetio branches are so ancient.  So I had to manually create and apply fixes for both of those branches. 

The 1.1 branch has no `dotRandom` or `phet.joist.random` for random-number generation, so (after discussion on Slack) I went with `Math.random`. The commit is 20f7692.  

Steps for the 1.1.24 maintence release were:

% cd perennial
% grunt checkout-target --repo=color-vision --target=1.1
// manually edit SingleBulbPhotonBeam.js and apply the change in 20f7692
% cd color-vision
% grunt
// manually test local build
% cd perennial
% grunt rc --repo=color-vision --brands=phet --branch=1.1
// wait for completion email from build server
// manually test 1.1.24-rc.1 at https://phet-dev.colorado.edu/html/color-vision/1.1.24-rc.1
% grunt production --repo=color-vision --brands=phet --branch=1.1
// wait for completion email from build server
// manually test 1.1.24 for English and a few other locales at https://phet.colorado.edu/en/simulation/color-vision


Steps for maintenance release 1.2.16-phetio

% cd perennial
%  grunt checkout-target --repo=color-vision --target=1.2-phetio
% cd color-vision
// manually edit SingleBulbPhotonBeam.js and apply the change in fcb1b1b
% grunt --brand=phet-io
// manually test local build in Instance Proxies wrapper
% cd perennial
% grunt rc --repo=color-vision --brands=phet-io --branch=1.2-phetio
// manually test 1.2.16-rc.1 in Events Colorized wrapper at https://phet-dev.colorado.edu/html/color-vision/1.2.16-phetiorc.1/wrappers/ (password required)
% grunt production --repo=color-vision --brands=phet-io --branch=1.2-phetio
// manually test all wrappers at https://phet-io.colorado.edu/sims/color-vision/1.2/wrappers/index/

**Comment by pixelzoom** [comment] 2021-02-03 00:05
This work is done.  The maintenance releases are:

1.1.24 at https://phet.colorado.edu/en/simulation/color-vision
1.2.16-phetio at https://phet-io.colorado.edu/sims/color-vision/1.2/wrappers/index/

@arouinfar @kathy-phet would you like to spot check?

@kathy-phet please reply to the user who reported this, then close this issue.

**Comment by kathy-phet** [comment] 2021-02-03 00:20
I checked it on phet.colorado.edu and phet-io.colorado.edu and it looks great. Thanks, @pixelzoom for jumping through those hoops for an older sim! Here is the new photon colors: 
![image](https://user-images.githubusercontent.com/5096804/106679966-ec4fcb80-657a-11eb-8cd0-2c8ca28f27ca.png)

**Comment by kathy-phet** [comment] 2021-02-03 00:21
I'll write the faculty member. @arouinfar - please close once you have done your spot check.

**Comment by arouinfar** [comment] 2021-02-03 15:50
Looks great, thanks @pixelzoom!

**Closed by arouinfar** 2021-02-03 15:50 UTC
Labels: status:ready-for-review, type:bug, type:user-feedback
