### ISSUE TITLE
Reset All Button overlap on RGB Screen

### ISSUE THREAD

**Issue by zepumph** [phetsims/color-vision#114] opened 2017-05-03 20:15 UTC
![image](https://cloud.githubusercontent.com/assets/6856943/25679537/effe1a88-300a-11e7-8365-fa2bcb33c214.png)

**Comment by pixelzoom** [comment] 2017-06-12 21:04
Duplicate of https://github.com/phetsims/sun/issues/293.  This has been fixed. Closing.

**Closed by pixelzoom** 2017-06-12 21:04 UTC
